version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g expo-cli

  pre_build:
    commands:
      - npm install --force

  build:
    commands:
      - expo build:android -t apk

cache:
  paths:
    - './node_modules/**/*'